'use client'

import { useState } from 'react'
import { ArrowUpRight, Check, ChevronDown, Code2, Database, Github, Globe, Layers3, Linkedin, Mail, Menu, Network, Send, Server, Sparkles, X, Zap } from 'lucide-react'
import { experience, learningSkills, principles, professionalSkills, profile, projects, services, socials } from '@/data/profile'

const navItems = [['Work', 'work'], ['AI Engineering', 'ai'], ['Skills', 'skills'], ['About', 'about'], ['Contact', 'contact']]

function SectionHeading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) {
  return <div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div>
}

function Pill({ children, muted = false }: { children: React.ReactNode; muted?: boolean }) {
  return <span className={muted ? 'pill pill-muted' : 'pill'}>{children}</span>
}

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [selected, setSelected] = useState<(typeof projects)[number] | null>(null)
  const [sent, setSent] = useState(false)

  const go = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false) }

  return <main>
    <nav className="nav-shell"><div className="nav-inner"><button className="wordmark" onClick={() => go('home')}><span className="mark">AS</span><span>Akram Sulthan</span></button><div className="desktop-nav">{navItems.map(([label, id]) => <button key={id} onClick={() => go(id)}>{label}</button>)}</div><button className="nav-cta" onClick={() => go('contact')}>Let&apos;s Talk <ArrowUpRight size={15} /></button><button className="menu-button" aria-label="Toggle menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <div className="mobile-nav">{navItems.map(([label, id]) => <button key={id} onClick={() => go(id)}>{label}<ArrowUpRight size={15} /></button>)}</div>}</nav>

    <section id="home" className="hero page-grid"><div className="hero-copy"><div className="eyebrow"><span className="status-dot" /> {profile.role}</div><h1>{profile.intro}</h1><p className="hero-summary">{profile.summary}</p><p className="learning-line"><Sparkles size={16} /> {profile.learning}</p><div className="hero-actions"><button className="button-primary" onClick={() => go('contact')}>Let&apos;s work together <ArrowUpRight size={17} /></button><button className="button-ghost" onClick={() => go('work')}>View my work <ArrowUpRight size={17} /></button></div><p className="availability"><span className="status-dot" /> {profile.availability}</p></div><div className="code-card"><div className="code-top"><span><span className="window-dot red" /><span className="window-dot yellow" /><span className="window-dot green" /></span><span className="code-label">akram.build.ts</span><span>● live</span></div><div className="code-body"><p><span className="code-dim">01</span> <span className="code-key">const</span> <span className="code-name">engineer</span> = {'{'}</p><p><span className="code-dim">02</span> &nbsp; <span className="code-prop">focus</span>: <span className="code-string">&quot;real-world products&quot;</span>,</p><p><span className="code-dim">03</span> &nbsp; <span className="code-prop">frontend</span>: <span className="code-string">[&quot;React&quot;, &quot;Next.js&quot;]</span>,</p><p><span className="code-dim">04</span> &nbsp; <span className="code-prop">backend</span>: <span className="code-string">[&quot;Node&quot;, &quot;TypeScript&quot;]</span>,</p><p><span className="code-dim">05</span> &nbsp; <span className="code-prop">data</span>: <span className="code-string">[&quot;Postgres&quot;, &quot;MongoDB&quot;]</span>,</p><p><span className="code-dim">06</span> &nbsp; <span className="code-prop">curiosity</span>: <span className="code-string">[&quot;RAG&quot;, &quot;MCP&quot;, &quot;Agents&quot;]</span></p><p><span className="code-dim">07</span>{'}'}</p><div className="code-divider" /><p className="code-output"><span>→</span> shipping useful software<span className="cursor" /></p></div></div></section>

    <section className="stats page-grid"><div><strong>1.5<span>+</span></strong><small>Years professional experience</small></div><div><strong>15<span>+</span></strong><small>REST APIs architected</small></div><div><strong>1,500<span>+</span></strong><small>Algorithmic problems solved</small></div><div><strong>2<span>×</span></strong><small>Star of the Month</small></div></section>

    <section className="section page-grid"><SectionHeading eyebrow="The direction" title="Full stack by experience. AI by curiosity. Systems by mindset." copy="My professional foundation is in full-stack and backend engineering. The next layer is modern AI engineering and system design — explored with intent, not inflated claims." /><div className="trio-grid"><article className="feature-card featured"><span className="card-icon"><Layers3 /></span><h3>Full Stack Engineering</h3><p>Production web applications using React, Next.js, Node.js, TypeScript, PostgreSQL, MongoDB, and REST APIs.</p><div className="card-line" /><span className="card-index">01 / professional foundation</span></article><article className="feature-card"><span className="card-icon"><Sparkles /></span><h3>AI Engineering</h3><p>Learning and experimenting with RAG, MCP, AI agents, LLM applications, tool calling, and vector search.</p><div className="card-line" /><span className="card-index">02 / currently exploring</span></article><article className="feature-card"><span className="card-icon"><Network /></span><h3>System Design</h3><p>Strengthening knowledge in scalable architecture, API design, caching, queues, reliability, and trade-offs.</p><div className="card-line" /><span className="card-index">03 / currently learning</span></article></div></section>

    <section id="work" className="section section-border page-grid"><SectionHeading eyebrow="Selected work" title="Production systems and projects I&apos;ve worked on." /><div className="project-list">{projects.map((project, i) => <article className="project-row" key={project.title}><div className="project-number">0{i + 1}</div><div className="project-main"><span className="project-category">{project.category}</span><h3>{project.title}</h3><p>{project.description}</p><div className="pills">{project.technologies.map(t => <Pill key={t}>{t}</Pill>)}</div></div><button className="case-link" onClick={() => setSelected(project)}>View case study <ArrowUpRight size={16} /></button></article>)}</div></section>

    <section id="ai" className="section ai-section page-grid"><SectionHeading eyebrow="The next layer" title="Exploring the AI engineering stack." copy="A learning path toward building AI capabilities into real applications — not standalone demos." /><div className="ai-layout"><div className="stack-flow">{['LLMs', 'Prompting / Structured Output', 'RAG', 'Vector Search', 'Tool Calling', 'MCP', 'AI Agents', 'Production Applications'].map((step, i) => <div className="flow-step" key={step}><span>{String(i + 1).padStart(2, '0')}</span><strong>{step}</strong>{i < 7 && <ChevronDown size={16} />}</div>)}</div><div className="ai-notes"><article><span>01</span><h3>RAG</h3><p>Learning how to connect LLMs with external knowledge and application data.</p></article><article><span>02</span><h3>MCP</h3><p>Exploring how AI systems can interact with tools and external resources.</p></article><article><span>03</span><h3>AI agents</h3><p>Studying tool use, context, reasoning loops, and multi-step workflows.</p></article></div></div><div className="lab-header"><span className="eyebrow">AI engineering lab</span><span className="lab-note">Learning projects / coming soon</span></div><div className="lab-grid">{['RAG Knowledge Assistant', 'MCP Tool Server', 'AI Agent Workflow'].map((title, i) => <article className="lab-card" key={title}><div><span className="lab-index">0{i + 1}</span><span className="coming">Coming soon</span></div><h3>{title}</h3><p>{['A knowledge retrieval application using documents, embeddings, vector search, and an LLM.', 'A project exploring MCP servers, tools, and AI-to-system interaction.', 'An agentic application capable of using tools and external services.'][i]}</p></article>)}</div></section>

    <section id="skills" className="section section-border page-grid"><SectionHeading eyebrow="Engineering stack" title="Tools I use to turn ideas into products." /><div className="skill-block"><div className="skill-label"><span className="skill-dot" /> Professional stack</div><div className="skill-grid">{Object.entries(professionalSkills).map(([group, skills]) => <div className="skill-group" key={group}><h3>{group}</h3><div className="pills">{skills.map(s => <Pill key={s}>{s}</Pill>)}</div></div>)}</div></div><div className="skill-block learning-block"><div className="skill-label"><Sparkles size={16} /> Currently learning</div><div className="skill-grid">{Object.entries(learningSkills).map(([group, skills]) => <div className="skill-group" key={group}><h3>{group}</h3><div className="pills">{skills.map(s => <Pill muted key={s}>{s}</Pill>)}</div></div>)}</div></div></section>

    <section id="about" className="section about-section page-grid"><div className="about-copy"><SectionHeading eyebrow="About me" title="Engineering products that solve real problems." /><p>I&apos;m a Full Stack Software Developer with professional experience building production systems involving marketplace platforms, startup evaluation workflows, booking systems, payment integrations, HR management systems, REST APIs, RBAC, and database-driven applications.</p><p>My professional experience is rooted in full-stack, backend, and product engineering. Alongside that foundation, I&apos;m actively learning AI engineering, RAG, MCP, AI agents, and system design.</p></div><div className="role-card"><div className="role-top"><span className="status-dot" /> current role</div><h3>{experience.title}</h3><p className="company">{experience.company}</p><p>{experience.period}</p><div className="role-rule" /><p>{experience.description}</p><div className="role-projects">{projects.slice(0, 4).map(p => <span key={p.title}>{p.title}</span>)}</div></div></section>

    <section className="section philosophy section-border page-grid"><SectionHeading eyebrow="How I work" title="A practical engineering philosophy." /><div className="principle-grid">{principles.map(([title, copy], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>

    <section className="section proof page-grid"><div className="proof-copy"><SectionHeading eyebrow="Problem solving" title="I don&apos;t just build interfaces. I solve problems." copy="A strong computer science foundation shapes how I approach product work: understand the problem, choose the right abstraction, and build for the next change." /><button className="button-ghost" onClick={() => go('contact')}>Start a conversation <ArrowUpRight size={17} /></button></div><div className="achievement-list"><div><strong>1,500<span>+</span></strong><p>Algorithmic problems solved</p></div><div><strong>#2</strong><p>Institute rank on GeeksforGeeks</p></div><div><strong>67,486</strong><p>CodeChef country rank</p></div><div><strong>2<span>×</span></strong><p>Star of the Month at Shloka Solutions</p></div></div></section>

    <section className="section services-section section-border page-grid"><SectionHeading eyebrow="Freelance services" title="What I can build for you." copy="From a new product surface to the backend systems underneath it, I bring a full-stack perspective to practical product problems." /><div className="service-grid">{services.map(([title, copy], i) => <article key={title}><span className="service-index">0{i + 1}</span><h3>{title}</h3><p>{copy}</p><ArrowUpRight className="service-arrow" size={18} /></article>)}</div></section>

    <section className="section roadmap page-grid"><SectionHeading eyebrow="The path ahead" title="What I&apos;m learning next." /><div className="roadmap-track">{['Full Stack Engineering', 'Backend & Infrastructure', 'System Design', 'AI Engineering', 'Agentic Systems', 'AI-Powered Products'].map((item, i) => <div className="roadmap-item" key={item}><span>{String(i + 1).padStart(2, '0')}</span><h3>{item}</h3><p>{['Professional foundation', 'APIs · Databases · Docker · AWS', 'Scalability · Architecture · Trade-offs', 'LLMs · RAG · Embeddings · Tool calling', 'MCP · AI agents · AI workflows', 'Combining full-stack engineering + AI'][i]}</p></div>)}</div></section>

    <section id="contact" className="contact-section page-grid"><div className="contact-intro"><span className="eyebrow">Have a product idea?</span><h2>Let&apos;s build something useful.</h2><p>Tell me what you&apos;re working on, what&apos;s stuck, or what you&apos;d like to explore.</p><a href={`mailto:${profile.email}`} className="email-link">{profile.email} <ArrowUpRight size={16} /></a><p className="phone">{profile.phone}</p></div><form className="contact-form" onSubmit={(e) => { e.preventDefault(); setSent(true) }}><label>Name<input required placeholder="Your name" /></label><label>Email<input required type="email" placeholder="you@company.com" /></label><label>Project type<select defaultValue=""><option value="" disabled>Select one</option><option>Full stack application</option><option>Backend / API work</option><option>AI-powered feature</option><option>Something else</option></select></label><label>Message<textarea required placeholder="Tell me a little about the project..." rows={4} /></label><button className="button-primary" type="submit">{sent ? <><Check size={17} /> Message prepared</> : <><Send size={17} /> Start a conversation</>}</button><small>This form is a frontend placeholder. Please use the email above to reach me directly.</small></form></section>

    <footer className="footer page-grid"><div><button className="wordmark" onClick={() => go('home')}><span className="mark">AS</span><span>Akram Sulthan</span></button><p>{profile.role}</p></div><div className="footer-links"><a href={socials.github || '#'}>GitHub <ArrowUpRight size={14} /></a><a href={socials.linkedin || '#'}>LinkedIn <ArrowUpRight size={14} /></a><a href={`mailto:${profile.email}`}>Email <Mail size={14} /></a></div><p className="copyright">© 2026 Mohammed Akram Sulthan A. All rights reserved.</p></footer>

    {selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><article className="case-modal" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)} aria-label="Close case study"><X /></button><span className="eyebrow">{selected.category}</span><h2>{selected.title}</h2><p>{selected.description}</p><div className="modal-columns"><div><span className="modal-label">Engineering highlights</span><ul>{selected.highlights.map(h => <li key={h}><Check size={15} />{h}</li>)}</ul></div><div><span className="modal-label">Technology</span><div className="pills">{selected.technologies.map(t => <Pill key={t}>{t}</Pill>)}</div></div></div><div className="modal-note"><Code2 size={17} /> Professional project details are presented from the work documented in my resume.</div></article></div>}
  </main>
}
